var futbolistasObj = [];
var FutbolistasSugerencias = [];
var futbolistasRespaldo = [];
var futbolistaActual = [];
const futbolistas = [
  [
    "Gheorghe Hagi",
    "Farul Constanța",
    "Steaua București",
    "Real Madrid",
    "Brescia",
    "Barcelona",
    "Galatasaray",
  ],
  [
    "George Weah",
    "Monaco",
    "Paris SG",
    "AC Milan",
    "Chelsea",
    "AC Milan",
    "Manchester City",
    "Marseille",
    "Al-Jazira",
  ],
  [
    "Hugo Sánchez",
    "Pumas",
    "Atlético Madrid",
    "Real Madrid",
    "CF America",
    "Necaxa",
    "FC Dallas",
  ],
  [
    "Rafael Márquez",
    "Atlas",
    "Monaco",
    "Barcelona",
    "New York Red Bulls",
    "Verona",
    "Atlético de San Luis",
  ],
  [
    "Javier Hernández (Chicharito)",
    "Guadalajara",
    "Manchester United",
    "Real Madrid",
    "Bayer Leverkusen",
    "West Ham",
    "LA Galaxy",
  ],
  [
    "Cuauhtémoc Blanco",
    "CF America",
    "Real Valladolid",
    "Veracruz",
    "Chicago Fire",
    "Santos Laguna",
  ],
  [
    "Jorge Campos",
    "Pumas",
    "Atlante",
    "LA Galaxy",
    "Chicago Fire",
    "Cruz Azul",
    "Tigres",
  ],
  ["Claudio Suárez", "Pumas", "CD Guadalajara", "Tigres", "CD Chivas USA"],
  [
    "Andrés Guardado",
    "Atlas",
    "La Coruña",
    "Valencia",
    "PSV Eindhoven",
    "Betis",
    "LA Galaxy",
  ],
  ["Carlos Vela", "Guadalajara", "Arsenal", "Real Sociedad", "Los Angeles FC"],
  [
    "Guillermo Ochoa",
    "CF America",
    "Ajaccio",
    "Málaga",
    "Standard",
    "CF America",
    "Salernitana",
  ],
  [
    "Landon Donovan",
    "San Jose Earthquakes",
    "Bayer Leverkusen",
    "LA Galaxy",
    "Bayern Munich",
    "Everton",
  ],
  [
    "Clint Dempsey",
    "New England Revolution",
    "Fulham",
    "Tottenham Hotspur",
    "Seattle Sounders FC",
  ],
  [
    "Jozy Altidore",
    "New York Red Bulls",
    "Villarreal",
    "Hull",
    "Sunderland",
    "Toronto FC",
    "New England Revolution",
  ],
  ["Christian Pulisic", "Borussia Dortmund", "Chelsea", "AC Milan"],
  [
    "Diego Forlán",
    "Independiente",
    "Manchester United",
    "Villarreal",
    "Atlético Madrid",
    "Inter Milan",
    "Cerezo Osaka",
  ],
  [
    "Edinson Cavani",
    "Danubio",
    "Palermo",
    "Napoli",
    "Paris SG",
    "Manchester United",
    "Valencia",
    "Boca Juniors",
  ],
  [
    "Diego Godín",
    "Nacional",
    "Villarreal",
    "Atlético Madrid",
    "Inter Milan",
    "Cagliari",
    "Vélez Sarsfield",
  ],
  [
    "Juan Cuadrado",
    "Independiente Medellín",
    "Udinese",
    "Fiorentina",
    "Chelsea",
    "Juventus",
  ],
  ["David Ospina", "Atlético Nacional", "Nice", "Arsenal", "Napoli"],
  [
    "Alexis Sánchez",
    "Cobreloa",
    "Colo-Colo",
    "River Plate",
    "Udinese",
    "Barcelona",
    "Arsenal",
    "Manchester United",
    "Inter Milan",
    "Marseille",
  ],
  [
    "Arturo Vidal",
    "Colo-Colo",
    "Bayer Leverkusen",
    "Juventus",
    "Bayern Munich",
    "Barcelona",
    "Inter Milan",
    "Flamengo",
    "Athletico Paranaense",
  ],
  [
    "Gary Medel",
    "Universidad Católica",
    "Boca Juniors",
    "Sevilla",
    "Cardiff City",
    "Inter Milan",
    "Besiktas",
    "Bologna",
  ],
  [
    "Enner Valencia",
    "Emelec",
    "Pachuca",
    "West Ham",
    "Everton",
    "Tigres",
    "Fenerbahçe",
  ],
  [
    "Antonio Valencia",
    "El Nacional",
    "Villarreal",
    "Wigan",
    "Manchester United",
    "LDU Quito",
  ],
  [
    "Jefferson Montero",
    "Emelec",
    "Villarreal",
    "Betis",
    "Swansea City",
    "West Brom",
    "Birmingham City",
  ],
  [
    "Felipe Caicedo",
    "Manchester City",
    "Levante",
    "Lokomotiv Moscow",
    "Lazio",
    "Genoa",
    "Inter Milan",
  ],
  [
    "Renato Ibarra",
    "El Nacional",
    "Vitesse",
    "CF America",
    "Tijuana",
    "LDU Quito",
  ],
  [
    "Carlos Tevez",
    "Boca Juniors",
    "Corinthians",
    "West Ham",
    "Manchester United",
    "Manchester City",
    "Juventus",
    "Shanghai Shenhua",
  ],
  [
    "Javier Mascherano",
    "River Plate",
    "Corinthians",
    "West Ham",
    "Liverpool",
    "Barcelona",
    "Hebei FC",
    "Estudiantes de La Plata",
  ],
  [
    "Ángel Di María",
    "Rosario Central",
    "Benfica",
    "Real Madrid",
    "Manchester United",
    "Paris SG",
    "Juventus",
    "Benfica",
  ],
  [
    "Kun Agüero",
    "Independiente",
    "Atlético Madrid",
    "Manchester City",
    "Barcelona",
  ],
  [
    "Lionel Scaloni",
    "Newell's Old Boys",
    "Estudiantes de La Plata",
    "La Coruña",
    "Lazio",
    "West Ham",
    "Atalanta",
  ],
  [
    "Juan Román Riquelme",
    "Argentinos Juniors",
    "Boca Juniors",
    "Barcelona",
    "Villarreal",
    "Boca Juniors",
  ],
  [
    "Gabriel Batistuta",
    "Newell's Old Boys",
    "Boca Juniors",
    "Fiorentina",
    "Roma",
    "Inter Milan",
    "Al-Arabi",
  ],
  [
    "Ariel Ortega",
    "River Plate",
    "Valencia",
    "Sampdoria",
    "Parma Calcio 1913",
    "Fenerbahçe",
    "Newell's Old Boys",
    "River Plate",
  ],
  [
    "Marcelo Salas",
    "Universidad de Chile",
    "River Plate",
    "Lazio",
    "Juventus",
    "River Plate",
  ],
  [
    "Iván Zamorano",
    "Cobresal",
    "St. Gallen",
    "Sevilla",
    "Real Madrid",
    "Inter Milan",
    "CF America",
    "Colo-Colo",
  ],
  ["Alex", "Corinthians", "Cruzeiro", "Fenerbahçe", "Corinthians", "Miami FC"],
  ["Kaká", "São Paulo", "AC Milan", "Real Madrid", "Orlando City"],
  [
    "Ronaldinho",
    "Grêmio",
    "Paris SG",
    "Barcelona",
    "AC Milan",
    "Fluminense",
    "Atlético Mineiro",
  ],
  [
    "Romário",
    "Vasco da Gama",
    "PSV Eindhoven",
    "Barcelona",
    "Flamengo",
    "Valencia",
  ],
  [
    "Rivaldo",
    "Santa Cruz",
    "Mogi Mirim",
    "Corinthians",
    "Palmeiras",
    "La Coruña",
    "Barcelona",
    "AC Milan",
    "Cruzeiro",
    "Olympiacos",
    "AEK Athens",
    "Bunyodkor",
    "São Paulo",
    "Kabuscorp",
    "Mogi Mirim",
  ],
  ["Zico", "Flamengo", "Udinese", "Kashima Antlers"],
  [
    "Sócrates",
    "Botafogo-SP",
    "Corinthians",
    "Fiorentina",
    "Flamengo",
    "Santos",
  ],
  [
    "James Rodríguez",
    "Envigado",
    "Banfield",
    "Porto",
    "Monaco",
    "Real Madrid",
    "Bayern Munich",
    "Everton",
    "Al-Rayyan SC",
    "Olympiacos",
    "São Paulo",
  ],
  [
    "Juan Cuadrado",
    "Independiente Medellín",
    "Udinese",
    "Fiorentina",
    "Chelsea",
    "Juventus",
  ],
  ["David Ospina", "Atlético Nacional", "Nice", "Arsenal", "Napoli"],
  [
    "Okocha",
    "Eintracht Frankfurt",
    "Fenerbahçe",
    "Paris SG",
    "Bolton",
    "Qatar SC",
    "Hull",
  ],
  [
    "Michael Ballack",
    "Chemnitzer FC",
    "Kaiserslautern",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Chelsea",
    "Bayer Leverkusen",
  ],
  ["Oliver Kahn", "Karlsruher SC", "Bayern Munich"],
  [
    "Miroslav Klose",
    "FC 08 Homburg",
    "Kaiserslautern",
    "Werder Bremen",
    "Bayern Munich",
    "Lazio",
  ],
  ["Claudio Marchisio", "Juventus", "Zenit St Petersburg", "Juventus"],
  ["Giorgio Chiellini", "Livorno", "Fiorentina", "Juventus", "Los Angeles FC"],
  [
    "Andrea Barzagli",
    "Pistoiese",
    "Piacenza",
    "Ascoli",
    "Chievo",
    "Palermo",
    "Wolfsburg",
    "Juventus",
  ],
  [
    "Leonardo Bonucci",
    "Inter Milan",
    "Treviso",
    "Pisa",
    "Genoa",
    "Bari",
    "Juventus",
    "AC Milan",
    "Juventus",
    "Union Berlin",
  ],
  [
    "Dani Alves",
    "Bahia",
    "Sevilla",
    "Barcelona",
    "Juventus",
    "Paris SG",
    "São Paulo",
    "Barcelona",
    "Pumas",
  ],
  [
    "Philippe Coutinho",
    "Vasco da Gama",
    "Inter Milan",
    "Liverpool",
    "Barcelona",
    "Bayern Munich",
    "Aston Villa",
    "Al-Duhail SC",
  ],
  [
    "Roberto Firmino",
    "Figueirense",
    "Hoffenheim",
    "Liverpool",
    "Al-Ahli Saudi FC",
  ],
  [
    "Sadio Mané",
    "Metz",
    "Red Bull Salzburg",
    "Southampton",
    "Liverpool",
    "Bayern Munich",
    "Al Nassr FC",
  ],
  ["Bernardo Silva", "Benfica", "Monaco", "Manchester City"],
  [
    "Riyad Mahrez",
    "Le Havre",
    "Leicester City",
    "Manchester City",
    "Al-Ahli Saudi FC",
  ],
  ["Jan Oblak", "Olimpija Ljubljana", "Benfica", "Atlético Madrid"],
  ["João Félix", "Benfica", "Atlético Madrid", "Chelsea", "Barcelona"],
  ["Ansu Fati", "Barcelona", "Brighton"],
  ["Pedri", "Las Palmas", "Barcelona"],
  ["Gavi", "Barcelona"],
  ["Frenkie de Jong", "Willem II", "Ajax", "Barcelona"],
  ["Matthijs de Ligt", "Ajax", "Juventus", "Bayern Munich"],
  [
    "Jadon Sancho",
    "Watford",
    "Manchester City",
    "Borussia Dortmund",
    "Manchester United",
  ],
  ["Marcus Rashford", "Manchester United"],
  [
    "Bruno Fernandes",
    "Boavista",
    "Novara",
    "Udinese",
    "Sampdoria",
    "Sporting CP",
    "Manchester United",
  ],
  [
    "Harry Maguire",
    "Sheffield United",
    "Hull",
    "Leicester City",
    "Manchester United",
  ],
  ["Declan Rice", "West Ham United", "Arsenal"],
  ["Bukayo Saka", "Arsenal"],
  ["Mason Mount", "Vitesse", "Derby County", "Chelsea", "Manchester United"],
  ["Jack Grealish", "Notts County", "Aston Villa", "Manchester City"],
  [
    "Raheem Sterling",
    "Queens Park Rangers",
    "Liverpool",
    "Manchester City",
    "Chelsea",
  ],
  ["Kai Havertz", "Bayer Leverkusen", "Chelsea", "Arsenal"],
  ["Timo Werner", "Stuttgart", "RB Leipzig", "Chelsea", "RB Leipzig"],
  [
    "Erling Haaland",
    "Bryne",
    "Molde",
    "Red Bull Salzburg",
    "Borussia Dortmund",
    "Manchester City",
  ],
  ["Jude Bellingham", "Birmingham City", "Borussia Dortmund", "Real Madrid"],
  ["Jamal Musiala", "Southampton", "Chelsea", "Bayern Munich"],
  ["Alphonso Davies", "Vancouver Whitecaps", "Bayern Munich"],
  ["Joshua Kimmich", "RB Leipzig", "Bayern Munich"],
  ["Serge Gnabry", "Arsenal", "West Brom", "Werder Bremen", "Bayern Munich"],
  ["Leroy Sané", "Schalke 04", "Manchester City", "Bayern Munich"],
  ["Kingsley Coman", "Paris SG", "Juventus", "Bayern Munich"],
  [
    "Dayot Upamecano",
    "Valenciennes",
    "Red Bull Salzburg",
    "RB Leipzig",
    "Bayern Munich",
  ],
  ["Lucas Hernández", "Atlético Madrid", "Bayern Munich", "Paris SG"],
  [
    "Theo Hernández",
    "Atlético Madrid",
    "Alavés",
    "Real Madrid",
    "Real Sociedad",
    "AC Milan",
  ],
  [
    "Achraf Hakimi",
    "Real Madrid",
    "Borussia Dortmund",
    "Inter Milan",
    "Paris SG",
  ],
  ["Sergio Dest", "Ajax", "Barcelona", "AC Milan", "PSV Eindhoven"],
  ["Nicolò Barella", "Cagliari", "Inter Milan"],
  ["Lautaro Martínez", "Racing Club", "Inter Milan"],
  [
    "Romelu Lukaku",
    "Anderlecht",
    "Chelsea",
    "West Brom",
    "Everton",
    "Manchester United",
    "Inter Milan",
    "Chelsea",
    "Roma",
  ],
  ["Pelé", "Santos", "New York Cosmos"],
  [
    "Diego Maradona",
    "Argentinos Juniors",
    "Boca Juniors",
    "Barcelona",
    "Napoli",
    "Sevilla",
    "Newell's Old Boys",
  ],
  ["Lionel Messi", "Barcelona", "Paris SG", "Inter Miami"],
  [
    "Cristiano Ronaldo",
    "Sporting CP",
    "Manchester United",
    "Real Madrid",
    "Juventus",
    "Manchester United",
    "Al Nassr FC",
  ],
  ["Johan Cruyff", "Ajax", "Barcelona", "Feyenoord"],
  ["Zinedine Zidane", "Cannes", "Bordeaux", "Juventus", "Real Madrid"],
  ["Michel Platini", "Nancy", "Zenit St Petersburg", "Juventus"],
  [
    "Alfredo Di Stéfano",
    "River Plate",
    "Millonarios",
    "Real Madrid",
    "Espanyol",
  ],
  ["Franz Beckenbauer", "Bayern Munich", "New York Cosmos", "Hamburg"],
  ["George Best", "Manchester United", "Stockport County", "Fulham"],
  ["Gerd Müller", "Bayern Munich", "Fort Lauderdale Strickers"],
  [
    "Ronaldo Nazário",
    "Cruzeiro",
    "PSV Eindhoven",
    "Barcelona",
    "Inter Milan",
    "Real Madrid",
    "AC Milan",
    "Corinthians",
  ],
  [
    "Ronaldinho",
    "Grêmio",
    "Paris SG",
    "Barcelona",
    "AC Milan",
    "Fluminense",
    "Atlético Mineiro",
  ],
  ["Xavi", "Barcelona", "Al Sadd"],
  ["Andrés Iniesta", "Barcelona", "Vissel Kobe"],
  ["Paolo Maldini", "AC Milan"],
  ["Franco Baresi", "AC Milan"],
  [
    "Roberto Baggio",
    "Fiorentina",
    "Juventus",
    "AC Milan",
    "Bologna",
    "Inter Milan",
    "Brescia",
  ],
  ["Lev Yashin", "Dinamo Moscow"],
  [
    "Thierry Henry",
    "Monaco",
    "Juventus",
    "Arsenal",
    "Barcelona",
    "New York Red Bulls",
  ],
  ["Zico", "Flamengo", "Udinese", "Kashima Antlers"],
  [
    "Romário",
    "Vasco da Gama",
    "PSV Eindhoven",
    "Barcelona",
    "Flamengo",
    "Valencia",
  ],
  [
    "Hristo Stoichkov",
    "CSKA Sofia",
    "Barcelona",
    "Parma Calcio 1913",
    "Chicago Fire",
  ],
  ["Marco van Basten", "Ajax", "AC Milan"],
  [
    "Ruud Gullit",
    "Feyenoord",
    "PSV Eindhoven",
    "AC Milan",
    "Sampdoria",
    "Chelsea",
  ],
  [
    "Lothar Matthäus",
    "Borussia Mönchengladbach",
    "Bayern Munich",
    "Inter Milan",
  ],
  [
    "Gianluigi Buffon",
    "Parma Calcio 1913",
    "Juventus",
    "Paris SG",
    "Parma Calcio 1913",
  ],
  ["Iker Casillas", "Real Madrid", "Porto"],
  [
    "Samuel Eto'o",
    "Real Madrid",
    "Mallorca",
    "Barcelona",
    "Inter Milan",
    "Chelsea",
    "Everton",
  ],
  [
    "Didier Drogba",
    "Le Mans",
    "Guingamp",
    "Marseille",
    "Chelsea",
    "Shanghai Shenhua",
    "Galatasaray",
  ],
  ["Steven Gerrard", "Liverpool", "LA Galaxy"],
  [
    "Frank Lampard",
    "West Ham",
    "Chelsea",
    "Manchester City",
    "New York City FC",
  ],
  ["Paul Scholes", "Manchester United"],
  ["Ryan Giggs", "Manchester United"],
  ["Eric Cantona", "Auxerre", "Marseille", "Leeds", "Manchester United"],
  ["Roy Keane", "Nottingham Forest", "Manchester United", "Celtic"],
  [
    "Andrea Pirlo",
    "Brescia",
    "Inter Milan",
    "AC Milan",
    "Juventus",
    "New York City FC",
  ],
  ["Kaká", "São Paulo", "AC Milan", "Real Madrid", "Orlando City"],
  ["Neymar", "Santos", "Barcelona", "Paris SG", "Al Hilal", "Santos"],

  ["Karim Benzema", "Lyon", "Real Madrid", "Al Ittihad"],
  [
    "Luis Suárez",
    "Nacional",
    "FC Groningen",
    "Ajax",
    "Liverpool",
    "Barcelona",
    "Atlético Madrid",
    "Grêmio",
  ],
  ["Manuel Neuer", "Schalke 04", "Bayern Munich"],
  ["Philipp Lahm", "Bayern Munich"],
  [
    "Bastian Schweinsteiger",
    "Bayern Munich",
    "Manchester United",
    "Chicago Fire",
  ],
  [
    "Arjen Robben",
    "FC Groningen",
    "PSV Eindhoven",
    "Chelsea",
    "Real Madrid",
    "Bayern Munich",
  ],
  ["Wesley Sneijder", "Ajax", "Real Madrid", "Inter Milan", "Galatasaray"],
  [
    "Clarence Seedorf",
    "Ajax",
    "Sampdoria",
    "Real Madrid",
    "Inter Milan",
    "AC Milan",
    "Botafogo",
  ],
  [
    "David Beckham",
    "Manchester United",
    "Real Madrid",
    "LA Galaxy",
    "Paris SG",
  ],
  ["Raúl", "Real Madrid", "Schalke 04", "Al Sadd", "New York Cosmos"],
  [
    "Fernando Torres",
    "Atlético Madrid",
    "Liverpool",
    "Chelsea",
    "AC Milan",
    "Sagan Tosu",
  ],
  ["Xabi Alonso", "Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"],
  ["Carles Puyol", "Barcelona"],
  ["Sergio Ramos", "Sevilla", "Real Madrid", "Paris SG"],
  ["Ivan Rakitić", "FC Basel", "Schalke 04", "Sevilla", "Barcelona"],
  ["Luka Modrić", "Dinamo Zagreb", "Tottenham Hotspur", "Real Madrid"],
  ["Harry Kane", "Tottenham Hotspur", "Bayern Munich"],
  [
    "Mohamed Salah",
    "Al-Mokawloon al-Arab",
    "FC Basel",
    "Chelsea",
    "Fiorentina",
    "Roma",
    "Liverpool",
  ],
  ["Virgil van Dijk", "FC Groningen", "Celtic", "Southampton", "Liverpool"],
  [
    "Kevin De Bruyne",
    "Genk",
    "Chelsea",
    "Werder Bremen",
    "Wolfsburg",
    "Manchester City",
  ],
  ["Eden Hazard", "Lille", "Chelsea", "Real Madrid"],
  ["N'Golo Kanté", "Boulogne", "Caen", "Leicester City", "Chelsea"],
  ["Kylian Mbappé", "Monaco", "Paris SG", "Real Madrid"],
  [
    "Gabriel Batistuta",
    "Newell's Old Boys",
    "Boca Juniors",
    "Fiorentina",
    "Roma",
    "Inter Milan",
    "Al-Arabi",
  ],
  ["Alessandro Del Piero", "Padova", "Juventus", "Sydney FC", "Odisha"],
  ["Francesco Totti", "Roma"],
  ["Pavel Nedvěd", "Dukla Prague", "Sparta Prague", "Lazio", "Juventus"],

  [
    "Carlos Tevez",
    "Boca Juniors",
    "Corinthians",
    "West Ham United",
    "Manchester United",
    "Manchester City",
    "Juventus",
    "Shanghai Shenhua",
    "Boca Juniors",
  ],
  [
    "Javier Zanetti",
    "Talleres de Remedios de Escalada",
    "Banfield",
    "Inter Milan",
  ],
  [
    "Claudio Caniggia",
    "River Plate",
    "Verona",
    "Atalanta",
    "Roma",
    "Benfica",
    "Boca Juniors",
    "Atalanta",
    "Dundee",
    "Rangers",
    "Qatar SC",
  ],
  [
    "Enzo Francescoli",
    "Montevideo Wanderers",
    "River Plate",
    "Racing Club",
    "Cagliari",
    "Marseille",
    "River Plate",
  ],

  ["Rui Costa", "Benfica", "Fiorentina", "AC Milan"],
  ["Luís Figo", "Sporting CP", "Barcelona", "Real Madrid", "Inter Milan"],
  [
    "Patrick Vieira",
    "Cannes",
    "AC Milan",
    "Arsenal",
    "Juventus",
    "Inter Milan",
    "Manchester City",
  ],
  ["Dennis Bergkamp", "Ajax", "Inter Milan", "Arsenal"],
  [
    "Robert Lewandowski",
    "Znicz Pruszków",
    "Lech Poznań",
    "Borussia Dortmund",
    "Bayern Munich",
    "Barcelona",
  ],
  ["Sergio Busquets", "Barcelona", "Inter Miami"],
  ["Gerard Piqué", "Manchester United", "Zaragoza", "Barcelona"],
  ["Jordi Alba", "Cornellà", "Valencia", "Barcelona", "Inter Miami"],
  [
    "Cesc Fàbregas",
    "Barcelona",
    "Arsenal",
    "Barcelona",
    "Chelsea",
    "Monaco",
    "Como",
  ],
  [
    "Robin van Persie",
    "Excelsior",
    "Feyenoord",
    "Arsenal",
    "Manchester United",
    "Fenerbahçe",
    "Feyenoord",
  ],
  [
    "Edinson Cavani",
    "Danubio",
    "Palermo",
    "Napoli",
    "Paris SG",
    "Manchester United",
    "Valencia",
    "Boca Juniors",
  ],
  [
    "Radamel Falcao",
    "River Plate",
    "Porto",
    "Atlético Madrid",
    "Monaco",
    "Chelsea",
    "Manchester United",
    "Galatasaray",
    "Vallecano",
  ],
  ["Marcelo", "Fluminense", "Real Madrid", "Olympiacos", "Fluminense"],
  ["Casemiro", "São Paulo", "Porto", "Real Madrid", "Manchester United"],
  [
    "Toni Kroos",
    "Bayern Munich",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Real Madrid",
  ],
  [
    "Mesut Özil",
    "Schalke 04",
    "Werder Bremen",
    "Real Madrid",
    "Arsenal",
    "Fenerbahçe",
    "İstanbul Başakşehir",
  ],
  [
    "Gareth Bale",
    "Southampton",
    "Tottenham Hotspur",
    "Real Madrid",
    "Tottenham Hotspur",
    "Los Angeles FC",
  ],
  ["Luka Modrić", "Dinamo Zagreb", "Tottenham Hotspur", "Real Madrid"],
  ["Vincent Kompany", "Anderlecht", "Hamburg", "Manchester City", "Anderlecht"],
  [
    "Yaya Touré",
    "Waasland-Beveren",
    "Metalurh Donetsk",
    "Olympiacos",
    "Monaco",
    "Barcelona",
    "Manchester City",
    "Olympiacos",
    "Qingdao Huanghai",
  ],
  [
    "David Silva",
    "Valencia",
    "Eibar",
    "Celta de Vigo",
    "Valencia",
    "Manchester City",
    "Real Sociedad",
  ],
  [
    "Ángel Di María",
    "Rosario Central",
    "Benfica",
    "Real Madrid",
    "Manchester United",
    "Paris SG",
    "Juventus",
    "Benfica",
  ],
  [
    "Thiago Silva",
    "Fluminense",
    "AC Milan",
    "Paris SG",
    "Chelsea",
    "Fluminense",
  ],
  [
    "Zlatan Ibrahimović",
    "Malmö FF",
    "Ajax",
    "Juventus",
    "Inter Milan",
    "Barcelona",
    "AC Milan",
    "Paris SG",
    "Manchester United",
    "LA Galaxy",
    "AC Milan",
  ],
];
