var futbolistasObj = [];
var FutbolistasSugerencias = [];
var futbolistasRespaldo = [];
var futbolistaActual = [];
var contador = 1;
var futbolistas = [
  [
    "Gheorghe Hagi",
    "Farul Constanța",
    "Steaua București",
    "Real Madrid",
    "Brescia",
    "Barcelona",
    "Galatasaray",
  ],
  [
    "George Weah",
    "Monaco",
    "Paris SG",
    "AC Milan",
    "Chelsea",
    "AC Milan",
    "Manchester City",
    "Marseille",
    "Al-Jazira",
  ],
  [
    "Hugo Sánchez",
    "Pumas",
    "Atlético Madrid",
    "Real Madrid",
    "CF America",
    "Necaxa",
    "FC Dallas",
  ],
  [
    "Rafael Márquez",
    "Atlas",
    "Monaco",
    "Barcelona",
    "New York Red Bulls",
    "Verona",
    "Atlético de San Luis",
  ],
  [
    "Javier Hernández (Chicharito)",
    "Guadalajara",
    "Manchester United",
    "Real Madrid",
    "Bayer Leverkusen",
    "West Ham",
    "LA Galaxy",
  ],
  [
    "Cuauhtémoc Blanco",
    "CF America",
    "Real Valladolid",
    "Veracruz",
    "Chicago Fire",
    "Santos Laguna",
  ],
  [
    "Jorge Campos",
    "Pumas",
    "Atlante",
    "LA Galaxy",
    "Chicago Fire",
    "Cruz Azul",
    "Tigres",
  ],
  ["Claudio Suárez", "Pumas", "CD Guadalajara", "Tigres", "CD Chivas USA"],
  [
    "Andrés Guardado",
    "Atlas",
    "La Coruña",
    "Valencia",
    "PSV Eindhoven",
    "Betis",
    "LA Galaxy",
  ],
  ["Carlos Vela", "Guadalajara", "Arsenal", "Real Sociedad", "Los Angeles FC"],
  [
    "Guillermo Ochoa",
    "CF America",
    "Ajaccio",
    "Málaga",
    "Standard",
    "CF America",
    "Salernitana",
  ],
  [
    "Landon Donovan",
    "San Jose Earthquakes",
    "Bayer Leverkusen",
    "LA Galaxy",
    "Bayern Munich",
    "Everton",
  ],
  [
    "Clint Dempsey",
    "New England Revolution",
    "Fulham",
    "Tottenham Hotspur",
    "Seattle Sounders FC",
  ],
  [
    "Jozy Altidore",
    "New York Red Bulls",
    "Villarreal",
    "Hull",
    "Sunderland",
    "Toronto FC",
    "New England Revolution",
  ],
  ["Christian Pulisic", "Borussia Dortmund", "Chelsea", "AC Milan"],
  [
    "Diego Forlán",
    "Independiente",
    "Manchester United",
    "Villarreal",
    "Atlético Madrid",
    "Inter Milan",
    "Cerezo Osaka",
  ],
  [
    "Edinson Cavani",
    "Danubio",
    "Palermo",
    "Napoli",
    "Paris SG",
    "Manchester United",
    "Valencia",
    "Boca Juniors",
  ],
  [
    "Diego Godín",
    "Nacional",
    "Villarreal",
    "Atlético Madrid",
    "Inter Milan",
    "Cagliari",
    "Vélez Sarsfield",
  ],
  [
    "Juan Cuadrado",
    "Independiente Medellín",
    "Udinese",
    "Fiorentina",
    "Chelsea",
    "Juventus",
  ],
  ["David Ospina", "Atlético Nacional", "Nice", "Arsenal", "Napoli"],
  [
    "Alexis Sánchez",
    "Cobreloa",
    "Colo-Colo",
    "River Plate",
    "Udinese",
    "Barcelona",
    "Arsenal",
    "Manchester United",
    "Inter Milan",
    "Marseille",
  ],
  [
    "Arturo Vidal",
    "Colo-Colo",
    "Bayer Leverkusen",
    "Juventus",
    "Bayern Munich",
    "Barcelona",
    "Inter Milan",
    "Flamengo",
    "Athletico Paranaense",
  ],
  [
    "Gary Medel",
    "Universidad Católica",
    "Boca Juniors",
    "Sevilla",
    "Cardiff City",
    "Inter Milan",
    "Besiktas",
    "Bologna",
  ],
  [
    "Enner Valencia",
    "Emelec",
    "Pachuca",
    "West Ham",
    "Everton",
    "Tigres",
    "Fenerbahçe",
  ],
  [
    "Antonio Valencia",
    "El Nacional",
    "Villarreal",
    "Wigan",
    "Manchester United",
    "LDU Quito",
  ],
  [
    "Jefferson Montero",
    "Emelec",
    "Villarreal",
    "Betis",
    "Swansea City",
    "West Brom",
    "Birmingham City",
  ],
  [
    "Felipe Caicedo",
    "Manchester City",
    "Levante",
    "Lokomotiv Moscow",
    "Lazio",
    "Genoa",
    "Inter Milan",
  ],
  [
    "Renato Ibarra",
    "El Nacional",
    "Vitesse",
    "CF America",
    "Tijuana",
    "LDU Quito",
  ],
  [
    "Carlos Tevez",
    "Boca Juniors",
    "Corinthians",
    "West Ham",
    "Manchester United",
    "Manchester City",
    "Juventus",
    "Shanghai Shenhua",
  ],
  [
    "Javier Mascherano",
    "River Plate",
    "Corinthians",
    "West Ham",
    "Liverpool",
    "Barcelona",
    "Hebei FC",
    "Estudiantes de La Plata",
  ],
  [
    "Kun Agüero",
    "Independiente",
    "Atlético Madrid",
    "Manchester City",
    "Barcelona",
  ],
  [
    "Lionel Scaloni",
    "Newell's Old Boys",
    "Estudiantes de La Plata",
    "La Coruña",
    "Lazio",
    "West Ham",
    "Atalanta",
  ],
  [
    "Juan Román Riquelme",
    "Argentinos Juniors",
    "Boca Juniors",
    "Barcelona",
    "Villarreal",
    "Boca Juniors",
  ],
  [
    "Gabriel Batistuta",
    "Newell's Old Boys",
    "Boca Juniors",
    "Fiorentina",
    "Roma",
    "Inter Milan",
    "Al-Arabi",
  ],
  [
    "Ariel Ortega",
    "River Plate",
    "Valencia",
    "Sampdoria",
    "Parma Calcio 1913",
    "Fenerbahçe",
    "Newell's Old Boys",
    "River Plate",
  ],
  [
    "Marcelo Salas",
    "Universidad de Chile",
    "River Plate",
    "Lazio",
    "Juventus",
    "River Plate",
  ],
  [
    "Iván Zamorano",
    "Cobresal",
    "St. Gallen",
    "Sevilla",
    "Real Madrid",
    "Inter Milan",
    "CF America",
    "Colo-Colo",
  ],
  ["Alex", "Corinthians", "Cruzeiro", "Fenerbahçe", "Corinthians", "Miami FC"],
  ["Kaká", "São Paulo", "AC Milan", "Real Madrid", "Orlando City"],
  [
    "Ronaldinho",
    "Grêmio",
    "Paris SG",
    "Barcelona",
    "AC Milan",
    "Fluminense",
    "Atlético Mineiro",
  ],
  [
    "Romário",
    "Vasco da Gama",
    "PSV Eindhoven",
    "Barcelona",
    "Flamengo",
    "Valencia",
  ],
  [
    "Rivaldo",
    "Santa Cruz",
    "Mogi Mirim",
    "Corinthians",
    "Palmeiras",
    "La Coruña",
    "Barcelona",
    "AC Milan",
    "Cruzeiro",
    "Olympiacos",
    "AEK Athens",
    "Bunyodkor",
    "São Paulo",
    "Kabuscorp",
    "Mogi Mirim",
  ],
  ["Zico", "Flamengo", "Udinese", "Kashima Antlers"],
  [
    "Sócrates",
    "Botafogo-SP",
    "Corinthians",
    "Fiorentina",
    "Flamengo",
    "Santos",
  ],
  [
    "James Rodríguez",
    "Envigado",
    "Banfield",
    "Porto",
    "Monaco",
    "Real Madrid",
    "Bayern Munich",
    "Everton",
    "Al-Rayyan SC",
    "Olympiacos",
    "São Paulo",
  ],
  [
    "Juan Cuadrado",
    "Independiente Medellín",
    "Udinese",
    "Fiorentina",
    "Chelsea",
    "Juventus",
  ],
  ["David Ospina", "Atlético Nacional", "Nice", "Arsenal", "Napoli"],
  [
    "Okocha",
    "Eintracht Frankfurt",
    "Fenerbahçe",
    "Paris SG",
    "Bolton",
    "Qatar SC",
    "Hull",
  ],
  [
    "Michael Ballack",
    "Chemnitzer FC",
    "Kaiserslautern",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Chelsea",
    "Bayer Leverkusen",
  ],
  ["Oliver Kahn", "Karlsruher SC", "Bayern Munich"],
  [
    "Miroslav Klose",
    "FC 08 Homburg",
    "Kaiserslautern",
    "Werder Bremen",
    "Bayern Munich",
    "Lazio",
  ],
  ["Claudio Marchisio", "Juventus", "Zenit St Petersburg", "Juventus"],
  ["Giorgio Chiellini", "Livorno", "Fiorentina", "Juventus", "Los Angeles FC"],
  [
    "Andrea Barzagli",
    "Pistoiese",
    "Piacenza",
    "Ascoli",
    "Chievo",
    "Palermo",
    "Wolfsburg",
    "Juventus",
  ],
  [
    "Leonardo Bonucci",
    "Inter Milan",
    "Treviso",
    "Pisa",
    "Genoa",
    "Bari",
    "Juventus",
    "AC Milan",
    "Juventus",
    "Union Berlin",
  ],
  [
    "Dani Alves",
    "Bahia",
    "Sevilla",
    "Barcelona",
    "Juventus",
    "Paris SG",
    "São Paulo",
    "Barcelona",
    "Pumas",
  ],
  [
    "Philippe Coutinho",
    "Vasco da Gama",
    "Inter Milan",
    "Liverpool",
    "Barcelona",
    "Bayern Munich",
    "Aston Villa",
    "Al-Duhail SC",
  ],
  [
    "Roberto Firmino",
    "Figueirense",
    "Hoffenheim",
    "Liverpool",
    "Al-Ahli Saudi FC",
  ],
  [
    "Sadio Mané",
    "Metz",
    "Red Bull Salzburg",
    "Southampton",
    "Liverpool",
    "Bayern Munich",
    "Al Nassr FC",
  ],
  ["Bernardo Silva", "Benfica", "Monaco", "Manchester City"],
  [
    "Riyad Mahrez",
    "Le Havre",
    "Leicester City",
    "Manchester City",
    "Al-Ahli Saudi FC",
  ],
  ["Jan Oblak", "Olimpija Ljubljana", "Benfica", "Atlético Madrid"],
  ["João Félix", "Benfica", "Atlético Madrid", "Chelsea", "Barcelona"],
  ["Ansu Fati", "Barcelona", "Brighton"],
  ["Pedri", "Las Palmas", "Barcelona"],
  ["Gavi", "Barcelona"],
  ["Frenkie de Jong", "Willem II", "Ajax", "Barcelona"],
  ["Matthijs de Ligt", "Ajax", "Juventus", "Bayern Munich"],
  [
    "Jadon Sancho",
    "Watford",
    "Manchester City",
    "Borussia Dortmund",
    "Manchester United",
  ],
  ["Marcus Rashford", "Manchester United"],
  [
    "Bruno Fernandes",
    "Boavista",
    "Novara",
    "Udinese",
    "Sampdoria",
    "Sporting CP",
    "Manchester United",
  ],
  [
    "Harry Maguire",
    "Sheffield United",
    "Hull",
    "Leicester City",
    "Manchester United",
  ],
  ["Declan Rice", "West Ham United", "Arsenal"],
  ["Bukayo Saka", "Arsenal"],
  ["Mason Mount", "Vitesse", "Derby County", "Chelsea", "Manchester United"],
  ["Jack Grealish", "Notts County", "Aston Villa", "Manchester City"],
  [
    "Raheem Sterling",
    "Queens Park Rangers",
    "Liverpool",
    "Manchester City",
    "Chelsea",
  ],
  ["Kai Havertz", "Bayer Leverkusen", "Chelsea", "Arsenal"],
  ["Timo Werner", "Stuttgart", "RB Leipzig", "Chelsea", "RB Leipzig"],
  [
    "Erling Haaland",
    "Bryne",
    "Molde",
    "Red Bull Salzburg",
    "Borussia Dortmund",
    "Manchester City",
  ],
  ["Jude Bellingham", "Birmingham City", "Borussia Dortmund", "Real Madrid"],
  ["Jamal Musiala", "Southampton", "Chelsea", "Bayern Munich"],
  ["Alphonso Davies", "Vancouver Whitecaps", "Bayern Munich"],
  ["Joshua Kimmich", "RB Leipzig", "Bayern Munich"],
  ["Serge Gnabry", "Arsenal", "West Brom", "Werder Bremen", "Bayern Munich"],
  ["Leroy Sané", "Schalke 04", "Manchester City", "Bayern Munich"],
  ["Kingsley Coman", "Paris SG", "Juventus", "Bayern Munich"],
  [
    "Dayot Upamecano",
    "Valenciennes",
    "Red Bull Salzburg",
    "RB Leipzig",
    "Bayern Munich",
  ],
  ["Lucas Hernández", "Atlético Madrid", "Bayern Munich", "Paris SG"],
  [
    "Theo Hernández",
    "Atlético Madrid",
    "Alavés",
    "Real Madrid",
    "Real Sociedad",
    "AC Milan",
  ],
  [
    "Achraf Hakimi",
    "Real Madrid",
    "Borussia Dortmund",
    "Inter Milan",
    "Paris SG",
  ],
  ["Sergio Dest", "Ajax", "Barcelona", "AC Milan", "PSV Eindhoven"],
  ["Nicolò Barella", "Cagliari", "Inter Milan"],
  ["Lautaro Martínez", "Racing Club", "Inter Milan"],
  [
    "Romelu Lukaku",
    "Anderlecht",
    "Chelsea",
    "West Brom",
    "Everton",
    "Manchester United",
    "Inter Milan",
    "Chelsea",
    "Roma",
  ],
  ["Pelé", "Santos", "New York Cosmos"],
  [
    "Diego Maradona",
    "Argentinos Juniors",
    "Boca Juniors",
    "Barcelona",
    "Napoli",
    "Sevilla",
    "Newell's Old Boys",
  ],
  ["Lionel Messi", "Barcelona", "Paris SG", "Inter Miami"],
  [
    "Cristiano Ronaldo",
    "Sporting CP",
    "Manchester United",
    "Real Madrid",
    "Juventus",
    "Manchester United",
    "Al Nassr FC",
  ],
  ["Johan Cruyff", "Ajax", "Barcelona", "Feyenoord"],
  ["Zinedine Zidane", "Cannes", "Bordeaux", "Juventus", "Real Madrid"],
  ["Michel Platini", "Nancy", "Zenit St Petersburg", "Juventus"],
  [
    "Alfredo Di Stéfano",
    "River Plate",
    "Millonarios",
    "Real Madrid",
    "Espanyol",
  ],
  ["Franz Beckenbauer", "Bayern Munich", "New York Cosmos", "Hamburg"],
  ["George Best", "Manchester United", "Stockport County", "Fulham"],
  ["Gerd Müller", "Bayern Munich", "Fort Lauderdale Strickers"],
  [
    "Ronaldo Nazário",
    "Cruzeiro",
    "PSV Eindhoven",
    "Barcelona",
    "Inter Milan",
    "Real Madrid",
    "AC Milan",
    "Corinthians",
  ],
  [
    "Ronaldinho",
    "Grêmio",
    "Paris SG",
    "Barcelona",
    "AC Milan",
    "Fluminense",
    "Atlético Mineiro",
  ],
  ["Xavi", "Barcelona", "Al Sadd"],
  ["Andrés Iniesta", "Barcelona", "Vissel Kobe"],
  ["Paolo Maldini", "AC Milan"],
  ["Franco Baresi", "AC Milan"],
  [
    "Roberto Baggio",
    "Fiorentina",
    "Juventus",
    "AC Milan",
    "Bologna",
    "Inter Milan",
    "Brescia",
  ],
  ["Lev Yashin", "Dinamo Moscow"],
  [
    "Thierry Henry",
    "Monaco",
    "Juventus",
    "Arsenal",
    "Barcelona",
    "New York Red Bulls",
  ],
  ["Zico", "Flamengo", "Udinese", "Kashima Antlers"],
  [
    "Romário",
    "Vasco da Gama",
    "PSV Eindhoven",
    "Barcelona",
    "Flamengo",
    "Valencia",
  ],
  [
    "Hristo Stoichkov",
    "CSKA Sofia",
    "Barcelona",
    "Parma Calcio 1913",
    "Chicago Fire",
  ],
  ["Marco van Basten", "Ajax", "AC Milan"],
  [
    "Ruud Gullit",
    "Feyenoord",
    "PSV Eindhoven",
    "AC Milan",
    "Sampdoria",
    "Chelsea",
  ],
  [
    "Lothar Matthäus",
    "Borussia Mönchengladbach",
    "Bayern Munich",
    "Inter Milan",
  ],
  [
    "Gianluigi Buffon",
    "Parma Calcio 1913",
    "Juventus",
    "Paris SG",
    "Parma Calcio 1913",
  ],
  ["Iker Casillas", "Real Madrid", "Porto"],
  [
    "Samuel Eto'o",
    "Real Madrid",
    "Mallorca",
    "Barcelona",
    "Inter Milan",
    "Chelsea",
    "Everton",
  ],
  [
    "Didier Drogba",
    "Le Mans",
    "Guingamp",
    "Marseille",
    "Chelsea",
    "Shanghai Shenhua",
    "Galatasaray",
  ],
  ["Steven Gerrard", "Liverpool", "LA Galaxy"],
  [
    "Frank Lampard",
    "West Ham",
    "Chelsea",
    "Manchester City",
    "New York City FC",
  ],
  ["Paul Scholes", "Manchester United"],
  ["Ryan Giggs", "Manchester United"],
  ["Eric Cantona", "Auxerre", "Marseille", "Leeds", "Manchester United"],
  ["Roy Keane", "Nottingham Forest", "Manchester United", "Celtic"],
  [
    "Andrea Pirlo",
    "Brescia",
    "Inter Milan",
    "AC Milan",
    "Juventus",
    "New York City FC",
  ],
  ["Kaká", "São Paulo", "AC Milan", "Real Madrid", "Orlando City"],
  ["Neymar", "Santos", "Barcelona", "Paris SG", "Al Hilal", "Santos"],

  ["Karim Benzema", "Lyon", "Real Madrid", "Al Ittihad"],
  [
    "Luis Suárez",
    "Nacional",
    "FC Groningen",
    "Ajax",
    "Liverpool",
    "Barcelona",
    "Atlético Madrid",
    "Grêmio",
  ],
  ["Manuel Neuer", "Schalke 04", "Bayern Munich"],
  ["Philipp Lahm", "Bayern Munich"],
  [
    "Bastian Schweinsteiger",
    "Bayern Munich",
    "Manchester United",
    "Chicago Fire",
  ],
  [
    "Arjen Robben",
    "FC Groningen",
    "PSV Eindhoven",
    "Chelsea",
    "Real Madrid",
    "Bayern Munich",
  ],
  ["Wesley Sneijder", "Ajax", "Real Madrid", "Inter Milan", "Galatasaray"],
  [
    "Clarence Seedorf",
    "Ajax",
    "Sampdoria",
    "Real Madrid",
    "Inter Milan",
    "AC Milan",
    "Botafogo",
  ],
  [
    "David Beckham",
    "Manchester United",
    "Real Madrid",
    "LA Galaxy",
    "Paris SG",
  ],
  ["Raúl", "Real Madrid", "Schalke 04", "Al Sadd", "New York Cosmos"],
  [
    "Fernando Torres",
    "Atlético Madrid",
    "Liverpool",
    "Chelsea",
    "AC Milan",
    "Sagan Tosu",
  ],
  ["Xabi Alonso", "Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"],
  ["Carles Puyol", "Barcelona"],
  ["Sergio Ramos", "Sevilla", "Real Madrid", "Paris SG"],
  ["Ivan Rakitić", "FC Basel", "Schalke 04", "Sevilla", "Barcelona"],
  ["Luka Modrić", "Dinamo Zagreb", "Tottenham Hotspur", "Real Madrid"],
  ["Harry Kane", "Tottenham Hotspur", "Bayern Munich"],
  [
    "Mohamed Salah",
    "Al-Mokawloon al-Arab",
    "FC Basel",
    "Chelsea",
    "Fiorentina",
    "Roma",
    "Liverpool",
  ],
  ["Virgil van Dijk", "FC Groningen", "Celtic", "Southampton", "Liverpool"],
  [
    "Kevin De Bruyne",
    "Genk",
    "Chelsea",
    "Werder Bremen",
    "Wolfsburg",
    "Manchester City",
  ],
  ["Eden Hazard", "Lille", "Chelsea", "Real Madrid"],
  ["N'Golo Kanté", "Boulogne", "Caen", "Leicester City", "Chelsea"],
  ["Kylian Mbappé", "Monaco", "Paris SG", "Real Madrid"],
  [
    "Gabriel Batistuta",
    "Newell's Old Boys",
    "Boca Juniors",
    "Fiorentina",
    "Roma",
    "Inter Milan",
    "Al-Arabi",
  ],
  ["Alessandro Del Piero", "Padova", "Juventus", "Sydney FC", "Odisha"],
  ["Francesco Totti", "Roma"],
  ["Pavel Nedvěd", "Dukla Prague", "Sparta Prague", "Lazio", "Juventus"],

  [
    "Carlos Tevez",
    "Boca Juniors",
    "Corinthians",
    "West Ham United",
    "Manchester United",
    "Manchester City",
    "Juventus",
    "Shanghai Shenhua",
    "Boca Juniors",
  ],
  [
    "Javier Zanetti",
    "Talleres de Remedios de Escalada",
    "Banfield",
    "Inter Milan",
  ],
  [
    "Claudio Caniggia",
    "River Plate",
    "Verona",
    "Atalanta",
    "Roma",
    "Benfica",
    "Boca Juniors",
    "Atalanta",
    "Dundee",
    "Rangers",
    "Qatar SC",
  ],
  [
    "Enzo Francescoli",
    "Montevideo Wanderers",
    "River Plate",
    "Racing Club",
    "Cagliari",
    "Marseille",
    "River Plate",
  ],

  ["Rui Costa", "Benfica", "Fiorentina", "AC Milan"],
  ["Luís Figo", "Sporting CP", "Barcelona", "Real Madrid", "Inter Milan"],
  [
    "Patrick Vieira",
    "Cannes",
    "AC Milan",
    "Arsenal",
    "Juventus",
    "Inter Milan",
    "Manchester City",
  ],
  ["Dennis Bergkamp", "Ajax", "Inter Milan", "Arsenal"],
  [
    "Robert Lewandowski",
    "Znicz Pruszków",
    "Lech Poznań",
    "Borussia Dortmund",
    "Bayern Munich",
    "Barcelona",
  ],
  ["Sergio Busquets", "Barcelona", "Inter Miami"],
  ["Gerard Piqué", "Manchester United", "Zaragoza", "Barcelona"],
  ["Jordi Alba", "Cornellà", "Valencia", "Barcelona", "Inter Miami"],
  [
    "Cesc Fabregas",
    "Barcelona",
    "Arsenal",
    "Barcelona",
    "Chelsea",
    "Monaco",
    "Como",
  ],
  [
    "Robin van Persie",
    "Excelsior",
    "Feyenoord",
    "Arsenal",
    "Manchester United",
    "Fenerbahçe",
    "Feyenoord",
  ],
  [
    "Edinson Cavani",
    "Danubio",
    "Palermo",
    "Napoli",
    "Paris SG",
    "Manchester United",
    "Valencia",
    "Boca Juniors",
  ],
  [
    "Radamel Falcao",
    "River Plate",
    "Porto",
    "Atlético Madrid",
    "Monaco",
    "Chelsea",
    "Manchester United",
    "Galatasaray",
    "Vallecano",
  ],
  ["Marcelo", "Fluminense", "Real Madrid", "Olympiacos", "Fluminense"],
  ["Casemiro", "São Paulo", "Porto", "Real Madrid", "Manchester United"],
  [
    "Toni Kroos",
    "Bayern Munich",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Real Madrid",
  ],
  [
    "Mesut Özil",
    "Schalke 04",
    "Werder Bremen",
    "Real Madrid",
    "Arsenal",
    "Fenerbahçe",
    "İstanbul Başakşehir",
  ],
  [
    "Gareth Bale",
    "Southampton",
    "Tottenham Hotspur",
    "Real Madrid",
    "Tottenham Hotspur",
    "Los Angeles FC",
  ],
  ["Luka Modrić", "Dinamo Zagreb", "Tottenham Hotspur", "Real Madrid"],
  ["Vincent Kompany", "Anderlecht", "Hamburg", "Manchester City", "Anderlecht"],
  [
    "Yaya Touré",
    "Waasland-Beveren",
    "Metalurh Donetsk",
    "Olympiacos",
    "Monaco",
    "Barcelona",
    "Manchester City",
    "Olympiacos",
    "Qingdao Huanghai",
  ],
  [
    "David Silva",
    "Valencia",
    "Eibar",
    "Celta de Vigo",
    "Valencia",
    "Manchester City",
    "Real Sociedad",
  ],
  [
    "Ángel Di María",
    "Rosario Central",
    "Benfica",
    "Real Madrid",
    "Manchester United",
    "Paris SG",
    "Juventus",
    "Benfica",
  ],
  [
    "Thiago Silva",
    "Fluminense",
    "AC Milan",
    "Paris SG",
    "Chelsea",
    "Fluminense",
  ],
  [
    "Zlatan Ibrahimović",
    "Malmö FF",
    "Ajax",
    "Juventus",
    "Inter Milan",
    "Barcelona",
    "AC Milan",
    "Paris SG",
    "Manchester United",
    "LA Galaxy",
    "AC Milan",
  ],
];
var rankingActual = []; // Variable para almacenar el ranking actual

var preguntasTOP10 = [
  [
    "Máximos Goleadores de la Champions League",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Robert Lewandowski", "Poland"],
    ["Karim Benzema", "france"],
    ["Raúl González", "Spain"],
    ["Thomas Müller", "Germany"],
    ["Ruud van Nistelrooy", "Netherlands"],
    ["Kylian Mbappé", "france"],
    ["Thierry Henry", "france"],
    ["Zlatan Ibrahimović", "Sweden"],
  ],
  [
    "Máximos Goleadores de la Historia",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Josef Bican", "austria"],
    ["Pelé", "Brazil"],
    ["Romário", "Brazil"],
    ["Ferenc Puskás", "Hungary"],
    ["Erwin Helmchen", "Germany"],
    ["Robert Lewandowski", "Poland"],
    ["Jimmy Jones", "England"],
    ["Abe Lenstra", "Netherlands"],
  ],
  [
    "Máximos Asistidores de la Historia",
    ["Lionel Messi", "argentina"],
    ["Pelé", "Brazil"],
    ["Johan Cruyff", "Netherlands"],
    [" Thomas Müller", "Germany"],
    ["Luís Figo", "portugal"],
    ["Luis Suarez", "uruguay"],
    ["Angel Di María", "argentina"],
    ["Neymar", "Brazil"],
    ["Kevin De Bruyne", "Belgium"],
    ["David Beckam", "England"],
  ],
  [
    "Máximos Ganadores de la Historia",
    ["Lionel Messi", "argentina"],
    ["Dani Alves", "Brazil"],
    ["Andrés Iniesta", "Spain"],
    ["Gerard Piqué", "Spain"],
    ["Maxwell", "Brazil"],
    ["Angel Di María", "argentina"],
    ["Sergio Busquets", "spain"],
    ["Ryan Giggs", "Wales"],
    ["Cristiano Ronaldo", "portugal"],
    ["Kenny Dalglish", "Scotland"],
  ],
  [
    "Top 10 del Balón de Oro 2016",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Antoine Griezmann", "france"],
    ["Luis Suárez", "uruguay"],
    ["Neymar", "Brazil"],
    ["Gareth Bale", "Wales"],
    ["Riyad Mahrez", "Algeria"],
    ["Jamie Vardy", "England"],
    ["Pepe", "portugal"],
    ["Gianluigi Buffon", "Italy"],
  ],
  [
    "Máximos Goleadores de la Historia de los Mundiales",
    ["Miroslav Klose", "Germany"],
    ["Ronaldo Nazário", "Brazil"],
    ["Gerd Müller", "Germany"],
    ["Just Fontaine", "france"],
    ["Lionel Messi", "argentina"],
    ["Kylian Mbappé", "france"],
    ["Pelé", "Brazil"],
    ["Sándor Kocsis", "Hungary"],
    ["Jürgen Klinsmann", "Germany"],
    ["Teófilo Cubillas", "Peru"],
  ],
  [
    "Máximos Goleadores en Selección",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Ali Daei", "iran"],
    ["Sunil Chhetri", "Force India"],
    ["Mokhtar Dahari", "Malaysia"],
    ["Ali Mabkhout", "United Arab Emirates"],
    ["Romelu Lukaku", "iraq"],
    ["Ferenc Puskás", "Hungary"],
    ["Robert Lewandowski", "Poland"],
    ["Neymar", "Brazil"],
  ],
  [
    "Máximos Goleadores de Sudamérica",
    ["Lionel Messi", "argentina"],
    ["Neymar", "Brazil"],
    ["Pelé", "Brazil"],
    ["Luis Suárez", "uruguay"],
    ["Ronaldo Nazário", "Brazil"],
    ["Edinson Cavani", "uruguay"],
    ["Gabriel Batistuta", "argentina"],
    ["Romário", "Brazil"],
    ["Alexis Sánchez", "chile"],
    ["Zico", "Brazil"],
  ],
  [
    "Máximos Goleadores del Barcelona",
    ["Lionel Messi", "argentina"],
    ["César Rodríguez", "Spain"],
    ["Luis Suárez", "uruguay"],
    ["László Kubala", "Hungary"],
    ["Josep Samitier", "Spain"],
    ["Josep Escolà", "Spain"],
    ["Paulino Alcántara", "Philippines"],
    ["Rivaldo", "Brazil"],
    ["Samuel Eto'o", "Cameroon"],
    ["Ángel Arocha", "spain"],
  ],
  [
    "Máximos Goleadores del Real Madrid",
    ["Cristiano Ronaldo", "portugal"],
    ["Karim Benzema", "france"],
    ["Raúl González", "Spain"],
    ["Alfredo Di Stéfano", "argentina"],
    ["Santillana", "Spain"],
    ["Ferenc Puskás", "Hungary"],
    ["Hugo Sánchez", "mexico"],
    ["Francisco Gento", "Spain"],
    ["Pirri", "Spain"],
    ["Emilio Butragueño", "Spain"],
  ],
  [
    "Top 10 del Balón de Oro 2005",
    ["Ronaldinho", "Brazil"],
    ["Frank Lampard", "England"],
    ["Steven Gerrard", "England"],
    ["Thierry Henry", "france"],
    ["Andriy Shevchenko", "Ukraine"],
    ["Paolo Maldini", "Italy"],
    ["Adriano", "Brazil"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Samuel Eto'o", "Cameroon"],
    ["Kaká", "Brazil"],
  ],
  [
    "Top 10 del Balón de Oro 2006",
    ["Fabio Cannavaro", "Italy"],
    ["Gianluigi Buffon", "Italy"],
    ["Thierry Henry", "france"],
    ["Ronaldinho", "Brazil"],
    ["Zinedine Zidane", "france"],
    ["Samuel Eto'o", "Cameroon"],
    ["Miroslav Klose", "Germany"],
    ["Didier Drogba", "Ivory Coast U23"],
    ["Andrea Pirlo", "Italy"],
    ["Deco", "portugal"],
  ],
  [
    "Top 10 del Balón de Oro 2007",
    ["Kaká", "Brazil"],
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Didier Drogba", "Ivory Coast U23"],
    ["Andrea Pirlo", "Italy"],
    ["Ruud van Nistelrooy", "Netherlands"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Cesc Fabregas", "Spain"],
    ["Robinho", "Brazil"],
    ["Francesco Totti", "Italy"],
  ],
  [
    "Top 10 del Balón de Oro 2008",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Fernando Torres", "Spain"],
    ["Iker Casillas", "Spain"],
    ["Xavi Hernández", "Spain"],
    ["Andrei Arshavin", "Russia"],
    ["David Villa", "Spain"],
    ["Kaká", "Brazil"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Steven Gerrard", "England"],
  ],
  [
    "Top 10 del Balón de Oro 2009",
    ["Lionel Messi", "argentina"],
    ["Cristiano Ronaldo", "portugal"],
    ["Xavi Hernández", "Spain"],
    ["Andrés Iniesta", "Spain"],
    ["Samuel Eto'o", "Cameroon"],
    ["Kaká", "Brazil"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Wayne Rooney", "England"],
    ["Didier Drogba", "Ivory Coast U23"],
    ["Steven Gerrard", "England"],
  ],
  [
    "Top 10 del Balón de Oro 2010",
    ["Lionel Messi", "argentina"],
    ["Andrés Iniesta", "Spain"],
    ["Xavi Hernández", "Spain"],
    ["Wesley Sneijder", "Netherlands"],
    ["Diego Forlán", "uruguay"],
    ["Cristiano Ronaldo", "portugal"],
    ["Iker Casillas", "Spain"],
    ["David Villa", "Spain"],
    ["Didier Drogba", "Ivory Coast U23"],
    ["Mesut Özil", "Germany"],
  ],
  [
    "Top 10 del Balón de Oro 2011",
    ["Lionel Messi", "argentina"],
    ["Cristiano Ronaldo", "portugal"],
    ["Xavi Hernández", "Spain"],
    ["Andrés Iniesta", "Spain"],
    ["Wayne Rooney", "England"],
    ["Neymar", "Brazil"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Robin van Persie", "Netherlands"],
    ["Iker Casillas", "Spain"],
    ["Luis Suárez", "uruguay"],
  ],
  [
    "Máximos Goleadores de la Premier League",
    ["Alan Shearer", "England"],
    ["Harry Kane", "England"],
    ["Wayne Rooney", "England"],
    ["Andrew Cole", "England"],
    ["Sergio Agüero", "argentina"],
    ["Mohamed Salah", "Egypt"],
    ["Frank Lampard", "England"],
    ["Thierry Henry", "france"],
    ["Robbie Fowler", "England"],
    ["Jermain Defoe", "England"],
  ],
  [
    "Máximos Goleadores de la Liga Española",
    ["Lionel Messi", "argentina"],
    ["Cristiano Ronaldo", "portugal"],
    ["Telmo Zarra", "Spain"],
    ["Karim Benzema", "france"],
    ["Hugo Sánchez", "mexico"],
    ["Raúl González", "Spain"],
    ["Alfredo Di Stéfano", "argentina"],
    ["César Rodríguez", "Spain"],
    ["Quini", "Spain"],
    ["Pahiño", "Spain"],
  ],
  [
    "Máximos Goleadores de la Serie A",
    ["Silvio Piola", "Italy"],
    ["Francesco Totti", "Italy"],
    ["Gunnar Nordahl", "Sweden"],
    ["Giuseppe Meazza", "Italy"],
    ["José Altafini", "Brazil"],
    ["Antonio Di Natale", "Italy"],
    ["Roberto Baggio", "Italy"],
    ["Ciro Inmmobile", "Italy"],
    ["Kurt Hamrin", "Sweden"],
    ["Alessandro Del Piero", "Italy"],
  ],
  [
    "Máximos Goleadores de la Bundesliga",
    ["Gerd Müller", "Germany"],
    ["Robert Lewandowski", "Poland"],
    ["Klaus Fischer", "Germany"],
    ["Jupp Heynckes", "Germany"],
    ["Manfred Burgsmüller", "Germany"],
    ["Claudio Pizarro", "peru"],
    ["Ulf Kirsten", "Germany"],
    ["Stefan Kuntz", "Germany"],
    ["Dieter Müller", "Germany"],
    ["Mario Gómez", "Germany"],
  ],
  [
    "Máximos Goleadores de la Liga Francesa",
    ["Delio Onnis", "argentina"],
    ["Bernard Lacombe", "france"],
    ["Hervé Revelli", "france"],
    ["Thadée Cisowski", "france"],
    ["Roger Piantoni", "france"],
    ["Kyliam Mbappe", "france"],
    ["Joseph Ujlaki", "france"],
    ["Fleury Di Nallo", "france"],
    ["Gunnar Andersson", "Sweden"],
    ["Carlos Bianchi", "argentina"],
  ],
  [
    "Máximos Goleadores de la Liga MX",
    ["Evanivaldo Castro 'Cabinho", "Brazil"],
    ["Carlos Hermosillo", "mexico"],
    ["Jared Borgetti", "mexico"],
    ["José Saturnino Cardozo", "paraguay"],
    ["Horacio Casarín", "mexico"],
    ["Oswaldo Castro", "chile"],
    ["Luis Roberto Alves 'Zague'", "mexico"],
    ["Adalberto Lopez", "mexico"],
    ["Eloir Perucci", "Brazil"],
    ["Sergio Lira", "mexico"],
  ],
  [
    "Máximos Goleadores de la Selección de Brasil",
    ["Neymar", "Brazil"],
    ["Pelé", "Brazil"],
    ["Ronaldo Nazário", "Brazil"],
    ["Romário", "Brazil"],
    ["Zico", "Brazil"],
    ["Bebeto", "Brazil"],
    ["Rivaldo", "Brazil"],
    ["Jairzinho", "Brazil"],
    ["Tostão", "Brazil"],
    ["Ademir", "Brazil"],
  ],
  [
    "Máximos Goleadores de la Selección de México",
    ["Javier Hernández", "mexico"],
    ["Jared Borgetti", "mexico"],
    ["Cuauhtémoc Blanco", "mexico"],
    ["Luis Hernández", "mexico"],
    ["Raul Jimenez", "mexico"],
    ["Carlos Hermosillo", "mexico"],
    ["Enrique Borja", "mexico"],
    ["Luis Roberto Alves 'Zague'", "mexico"],
    ["Hugo Sánchez", "mexico"],
    ["Luis García", "mexico"],
  ],
  [
    "Máximos Goleadores de la Selección de Argentina",
    ["Lionel Messi", "argentina"],
    ["Gabriel Batistuta", "argentina"],
    ["Sergio Agüero", "argentina"],
    ["Hernán Crespo", "argentina"],
    ["Diego Maradona", "argentina"],
    ["Lautaro Martinez", "argentina"],
    ["Gonzalo Higuaín", "argentina"],
    ["Ángel Di María", "argentina"],
    ["Luis Artime", "argentina"],
    ["Daniel Passarella", "argentina"],
  ],
  [
    "Top 10 del Balón de Oro 2012",
    ["Lionel Messi", "argentina"],
    ["Cristiano Ronaldo", "portugal"],
    ["Andrés Iniesta", "Spain"],
    ["Xavi Hernández", "Spain"],
    ["Radamel Falcao", "colombia"],
    ["Iker Casillas", "Spain"],
    ["Robin van Persie", "Netherlands"],
    ["Didier Drogba", "Ivory Coast U23"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Andrea Pirlo", "Italy"],
  ],
  [
    "Top 10 del Balón de Oro 2013",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Franck Ribéry", "france"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Neymar", "Brazil"],
    ["Andrés Iniesta", "Spain"],
    ["Xavi Hernández", "Spain"],
    ["Gareth Bale", "Wales"],
    ["Luis Suárez", "uruguay"],
    ["Mesut Özil", "Germany"],
  ],
  [
    "Top 10 del Balón de Oro 2014",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Manuel Neuer", "Germany"],
    ["Arjen Robben", "Netherlands"],
    ["Thomas Müller", "Germany"],
    ["Toni Kroos", "Germany"],
    ["Neymar", "Brazil"],
    ["James Rodríguez", "colombia"],
    ["Ángel Di María", "argentina"],
    ["Luis Suárez", "uruguay"],
  ],
  [
    "Top 10 del Balón de Oro 2015",
    ["Lionel Messi", "argentina"],
    ["Cristiano Ronaldo", "portugal"],
    ["Neymar", "Brazil"],
    ["Robert Lewandowski", "Poland"],
    ["Luis Suárez", "uruguay"],
    ["Thomas Müller", "Germany"],
    ["Manuel Neuer", "Germany"],
    ["Andrés Iniesta", "Spain"],
    ["Alexis Sánchez", "chile"],
    ["Paul Pogba", "france"],
  ],
  [
    "Top 10 del Balón de Oro 2017",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Neymar", "Brazil"],
    ["Gianluigi Buffon", "Italy"],
    ["Luka Modrić", "Croatia"],
    ["Sergio Ramos", "Spain"],
    ["Kylian Mbappé", "france"],
    ["N'Golo Kanté", "france"],
    ["Robert Lewandowski", "Poland"],
    ["Harry Kane", "England"],
  ],
  [
    "Top 10 del Balón de Oro 2018",
    ["Luka Modrić", "Croatia"],
    ["Cristiano Ronaldo", "portugal"],
    ["Antoine Griezmann", "france"],
    ["Kylian Mbappé", "france"],
    ["Lionel Messi", "argentina"],
    ["Mohamed Salah", "Egypt"],
    ["Raphaël Varane", "france"],
    ["Eden Hazard", "Belgium"],
    ["Kevin De Bruyne", "Belgium"],
    ["Harry Kane", "England"],
  ],
  [
    "Top 10 del Balón de Oro 2019",
    ["Lionel Messi", "argentina"],
    ["Virgil van Dijk", "Netherlands"],
    ["Cristiano Ronaldo", "portugal"],
    ["Sadio Mané", "senegal"],
    ["Mohamed Salah", "Egypt"],
    ["Kylian Mbappé", "france"],
    ["Alisson Becker", "Brazil"],
    ["Robert Lewandowski", "Poland"],
    ["Bernardo Silva", "portugal"],
    ["Riyad Mahrez", "Algeria"],
  ],
  [
    "Top 10 del Balón de Oro 2021",
    ["Lionel Messi", "argentina"],
    ["Robert Lewandowski", "Poland"],
    ["Jorginho", "Italy"],
    ["Karim Benzema", "france"],
    ["N'Golo Kanté", "france"],
    ["Cristiano Ronaldo", "portugal"],
    ["Mohamed Salah", "Egypt"],
    ["Kevin De Bruyne", "Belgium"],
    ["Kylian Mbappé", "france"],
    ["Gianluigi Donnarumma", "Italy"],
  ],
  [
    "Top 10 del Balón de Oro 2022",
    ["Karim Benzema", "france"],
    ["Sadio Mané", "senegal"],
    ["Kevin De Bruyne", "Belgium"],
    ["Robert Lewandowski", "Poland"],
    ["Mohamed Salah", "Egypt"],
    ["Kylian Mbappé", "france"],
    ["Thibaut Courtois", "Belgium"],
    ["Vinícius Júnior", "Brazil"],
    ["Luka Modrić", "Croatia"],
    ["Erling Haaland", "Norway"],
  ],
  [
    "Top 10 del Balón de Oro 2023",
    ["Lionel Messi", "argentina"],
    ["Erling Haaland", "Norway"],
    ["Kylian Mbappé", "france"],
    ["Kevin De Bruyne", "Belgium"],
    ["Rodri", "Spain"],
    ["Vinícius Júnior", "Brazil"],
    ["Julián Álvarez", "argentina"],
    ["Victor Osimhen", "nigeria"],
    ["Luka Modrić", "Croatia"],
    ["Harry Kane", "England"],
  ],
  [
    "Top 10 del Balón de Oro 2024",
    ["Erling Haaland", "Norway"],
    ["Vinícius Júnior", "Brazil"],
    ["Kylian Mbappé", "france"],
    ["Jude Bellingham", "England"],
    ["Rodri", "Spain"],
    ["Lionel Messi", "argentina"],
    ["Kevin De Bruyne", "Belgium"],
    ["Bukayo Saka", "England"],
    ["Victor Osimhen", "nigeria"],
    ["Julián Álvarez", "argentina"],
  ],
  [
    "Máximos Goleadores de la Selección de Francia",
    ["Olivier Giroud", "france"],
    ["Thierry Henry", "france"],
    ["Kylian Mbappé", "france"],
    ["Antoine Griezmann", "france"],
    ["Michel Platini", "france"],
    ["Karim Benzema", "france"],
    ["David Trezeguet", "france"],
    ["Zinedine Zidane", "france"],
    ["Just Fontine", "france"],
    ["Jean-Pierre Papin", "france"],
  ],
  [
    "Máximos Goleadores de la Selección de Alemania",
    ["Miroslav Klose", "Germany"],
    ["Gerd Müller", "Germany"],
    ["Lukas Podolski", "Germany"],
    ["Jürgen Klinsmann", "Germany"],
    ["Rudi Völler", "Germany"],
    ["Karl-Heinz Rummenigge", "Germany"],
    ["Thomas Müller", "Germany"],
    ["Uwe Seeler", "Germany"],
    ["Michael Ballack", "Germany"],
    ["Oliver Bierhoff", "Germany"],
  ],
  [
    "Máximos Ganadores de Champions (Equipos)",
    ["Real Madrid", "Spain"],
    ["AC Milan", "Italy"],
    ["Bayern Múnich", "Germany"],
    ["Barcelona", "Spain"],
    ["Liverpool", "England"],
    ["Manchester United", "England"],
    ["Inter de Milán", "Italy"],
    ["Juventus", "Italy"],
    ["Ajax", "Netherlands"],
    ["Benfica", "portugal"],
  ],
  [
    "Máximos Ganadores de Copa Libertadores (Equipos)",
    ["Independiente", "argentina"],
    ["Boca Juniors", "argentina"],
    ["River Plate", "argentina"],
    ["Peñarol", "uruguay"],
    ["Estudiantes", "argentina"],
    ["Gremio", "brazil"],
    ["Nacional", "uruguay"],
    ["Flamengo", "brazil"],
    ["Santos", "brazil"],
    ["Cruzeiro", "brazil"],
  ],
  [
    "Máximos Anotadores de Tiro Libre",
    ["Juninho Pernambucano", "Brazil"],
    ["Pelé", "Brazil"],
    ["Lionel Messi", "argentina"],
    ["Ronaldinho", "Brazil"],
    ["Victor Legrotaglie", "Italy"],
    ["David Beckham", "England"],
    ["Diego Maradona", "argentina"],
    ["Zico", "Brazil"],
    ["Cristiano Ronaldo", "portugal"],
    ["Ronald Koeman", "Netherlands"],
  ],
  [
    "Máximos Anotadores de Penal",
    ["Cristiano Ronaldo", "portugal"],
    ["Lionel Messi", "argentina"],
    ["Romário", "Brazil"],
    ["Ronald Koeman", "Netherlands"],
    ["Hugo Sánchez", "mexico"],
    ["Roberto Baggio", "Italy"],
    ["Francesco Totti", "Italy"],
    ["Cuauhtémoc Blanco", "mexico"],
    ["Zlatan Ibrahimović", "Sweden"],
    ["Robert Lewandowski", "Poland"],
  ],
];
